<footer id="footer">
	<div class="footer-blankspace"></div>
	<div class="footer-content">
		<nav class="footer-column">
			<a href="index.php">Home</a>
			<a href="store.php">Store</a>
			<a href="account.php">Account</a>
			<a href="cart.php">Shopping Cart</a>
		</nav>

		<section class="footer-column">
			<a href="#top" class="back-to-top">Back to Top</a>
		</section>

		<section class="footer-column">
			<img src="images/eating.gif" alt="Footer GIF" />
			<p>&copy; 2024 All Your Healthy Foods.</p>
			<p>All Rights Reserved.</p>
		</section>
	</div>
</footer>