<meta charset="UTF-8">
<meta name="description" content="Online Healthy Food Store" />
<meta name="keywords" content="HTML, CSS, PHP, MySQL" />
<meta name="author" content="Wholesome Guys"  />
<meta name="viewport" content="width=device-width, initial-scale=1.0"  />

<link href="styles/style.css" rel="stylesheet"  />
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.6.0.js" charset="utf-8"></script>

<title><?php echo $page_title; ?></title>