<header>
	<!-- Sidebar Menu -->
	<nav id="sidebar">
	  <ul class="sidebar-section flexlayout-column">
		<li class="logo flexlayout-leftside">
		  <a class="sidebar-link-expansion flexlayout" href="index.php">
		      <img src="images/healthy.png" width="50" height="50" alt="Logo" />
		  </a>
		</li>
		<li class="sidebar-link-shrinkage flexlayout-leftside">
		  <a class="sidebar-link-expansion flexlayout-leftside" href="index.php">
			<div class="sidebar-link-icon flexlayout">
			  <img src="images/home.png" width="25" height="25" alt="Home Icon" />
			</div>
			<span class="link-text">Home</span>
		  </a>
		</li>
		<li class="sidebar-link-shrinkage flexlayout-leftside">
		  <a class="sidebar-link-expansion flexlayout-leftside" href="store.php">
			<div class="sidebar-link-icon flexlayout">
				<img src="images/store.png" width="25" height="25" alt="Store Icon" />
			</div>
			<span class="link-text">Store</span>
		  </a>
		</li>
		<li class="sidebar-link-shrinkage flexlayout-leftside">
		  <a class="sidebar-link-expansion flexlayout-leftside" href="account.php">
			<div class="sidebar-link-icon flexlayout">
				<img src="images/account.png" width="25" height="25" alt="Account Icon" />
			</div>
			<span class="link-text">Account</span>
		  </a>
		</li>
		<li class="sidebar-link-shrinkage flexlayout-leftside">
		  <a class="sidebar-link-expansion flexlayout-leftside" href="cart.php">
			<div class="sidebar-link-icon flexlayout">
				<img src="images/cart.png" width="25" height="25" alt="Shopping Cart Icon" />
			</div>
			<span class="link-text">Shopping Cart</span>
		  </a>
		</li>
	  </ul>
	</nav>
</header>